"""Shared Census MSA definitions, IO, and validation utilities."""

from hhplab.msa.coverage import (
    MSA_COC_COVERAGE_COLUMNS,
    build_msa_coc_coverage,
    read_msa_coc_coverage,
    save_msa_coc_coverage,
    select_primary_msa_for_cocs,
)
from hhplab.msa.crosswalk import (
    ALLOCATION_SHARE_TOLERANCE,
    COC_MSA_BLOCK_POPULATION_CROSSWALK_COLUMNS,
    COC_MSA_CROSSWALK_COLUMNS,
    FULL_ALLOCATION_THRESHOLD,
    build_coc_msa_block_population_crosswalk,
    build_coc_msa_crosswalk,
    read_coc_msa_block_population_crosswalk,
    read_coc_msa_crosswalk,
    save_coc_msa_block_population_crosswalk,
    save_coc_msa_crosswalk,
    summarize_coc_msa_allocation,
)
from hhplab.msa.msa_boundaries import (
    download_msa_boundaries,
    ingest_msa_boundaries,
    read_msa_boundaries,
    validate_curated_msa_boundaries,
    write_msa_boundaries,
)
from hhplab.msa.msa_definitions import (
    DEFINITION_VERSION,
    DELINEATION_FILE_YEAR,
    MSA_AREA_TYPE,
    SOURCE_NAME,
    SOURCE_REF,
    WORKBOOK_FILENAME,
    build_county_membership_df,
    build_definitions_df,
    parse_delineation_workbook,
)
from hhplab.msa.msa_io import (
    download_delineation_rows,
    read_msa_county_membership,
    read_msa_definitions,
    validate_curated_msa,
    write_msa_artifacts,
)
from hhplab.msa.msa_validate import (
    MSAValidationResult,
    validate_msa_artifacts,
    validate_msa_boundaries,
)
from hhplab.msa.selectors import (
    TopMsaSelection,
    TopMsaSelectionDiagnostics,
    select_top_msa_ids_by_population,
    select_top_msa_ids_for_panel_spec,
)
from hhplab.msa.unemployment import (
    MSA_ACS5_UNEMPLOYMENT_COLUMNS,
    MSA_LAUS_UNEMPLOYMENT_COLUMNS,
    MSA_UNEMPLOYMENT_COMMON_COLUMNS,
    load_laus_msa_unemployment,
    resolve_msa_unemployment,
    validate_laus_years_available,
)

__all__ = [
    "ALLOCATION_SHARE_TOLERANCE",
    "COC_MSA_BLOCK_POPULATION_CROSSWALK_COLUMNS",
    "COC_MSA_CROSSWALK_COLUMNS",
    "DEFINITION_VERSION",
    "DELINEATION_FILE_YEAR",
    "FULL_ALLOCATION_THRESHOLD",
    "MSA_AREA_TYPE",
    "MSA_COC_COVERAGE_COLUMNS",
    "SOURCE_NAME",
    "SOURCE_REF",
    "WORKBOOK_FILENAME",
    "parse_delineation_workbook",
    "build_definitions_df",
    "build_county_membership_df",
    "build_coc_msa_block_population_crosswalk",
    "build_coc_msa_crosswalk",
    "build_msa_coc_coverage",
    "download_msa_boundaries",
    "download_delineation_rows",
    "ingest_msa_boundaries",
    "read_coc_msa_block_population_crosswalk",
    "read_coc_msa_crosswalk",
    "read_msa_boundaries",
    "read_msa_coc_coverage",
    "read_msa_definitions",
    "read_msa_county_membership",
    "save_coc_msa_block_population_crosswalk",
    "save_coc_msa_crosswalk",
    "save_msa_coc_coverage",
    "select_primary_msa_for_cocs",
    "summarize_coc_msa_allocation",
    "select_top_msa_ids_for_panel_spec",
    "select_top_msa_ids_by_population",
    "write_msa_boundaries",
    "write_msa_artifacts",
    "validate_curated_msa",
    "validate_curated_msa_boundaries",
    "MSAValidationResult",
    "validate_msa_artifacts",
    "validate_msa_boundaries",
    "TopMsaSelection",
    "TopMsaSelectionDiagnostics",
    "MSA_ACS5_UNEMPLOYMENT_COLUMNS",
    "MSA_LAUS_UNEMPLOYMENT_COLUMNS",
    "MSA_UNEMPLOYMENT_COMMON_COLUMNS",
    "load_laus_msa_unemployment",
    "resolve_msa_unemployment",
    "validate_laus_years_available",
]
