"""Canonical column names and reusable column groups."""

from __future__ import annotations

TOTAL_POPULATION = "total_population"
POPULATION_DENSITY_COLUMN = "population_density_per_sq_km"

GEO_ID_COLUMNS: tuple[str, ...] = (
    "geo_type",
    "geo_id",
    "coc_id",
    "metro_id",
    "msa_id",
    "county_fips",
    "tract_geoid",
)

ACS_MEASURE_COLUMNS: list[str] = [
    TOTAL_POPULATION,
    "adult_population",
    "population_below_poverty",
    "poverty_rate",
    "median_household_income",
    "median_gross_rent",
    "vacancy_rate",
    "rent_burden_30_plus",
    "unemployment_rate",
]

ACS1_MEASURE_COLUMNS: list[str] = [
    "unemployment_rate_acs1",
]

LAUS_MEASURE_COLUMNS: list[str] = [
    "labor_force",
    "employed",
    "unemployed",
    "unemployment_rate",
]

LAUS_MEASURE_CODES: dict[str, str] = {
    "unemployment_rate": "03",
    "unemployed": "04",
    "employed": "05",
    "labor_force": "06",
}

ACS5_SAE_COUNT_COLUMNS: list[str] = [
    "household_income_total",
    "household_income_lt_10000",
    "household_income_10000_to_14999",
    "household_income_15000_to_19999",
    "household_income_20000_to_24999",
    "household_income_25000_to_29999",
    "household_income_30000_to_34999",
    "household_income_35000_to_39999",
    "household_income_40000_to_44999",
    "household_income_45000_to_49999",
    "household_income_50000_to_59999",
    "household_income_60000_to_74999",
    "household_income_75000_to_99999",
    "household_income_100000_to_124999",
    "household_income_125000_to_149999",
    "household_income_150000_to_199999",
    "household_income_200000_plus",
    "gross_rent_distribution_total",
    "gross_rent_distribution_with_cash_rent",
    "gross_rent_distribution_cash_rent_lt_100",
    "gross_rent_distribution_cash_rent_100_to_149",
    "gross_rent_distribution_cash_rent_150_to_199",
    "gross_rent_distribution_cash_rent_200_to_249",
    "gross_rent_distribution_cash_rent_250_to_299",
    "gross_rent_distribution_cash_rent_300_to_349",
    "gross_rent_distribution_cash_rent_350_to_399",
    "gross_rent_distribution_cash_rent_400_to_449",
    "gross_rent_distribution_cash_rent_450_to_499",
    "gross_rent_distribution_cash_rent_500_to_549",
    "gross_rent_distribution_cash_rent_550_to_599",
    "gross_rent_distribution_cash_rent_600_to_649",
    "gross_rent_distribution_cash_rent_650_to_699",
    "gross_rent_distribution_cash_rent_700_to_749",
    "gross_rent_distribution_cash_rent_750_to_799",
    "gross_rent_distribution_cash_rent_800_to_899",
    "gross_rent_distribution_cash_rent_900_to_999",
    "gross_rent_distribution_cash_rent_1000_to_1249",
    "gross_rent_distribution_cash_rent_1250_to_1499",
    "gross_rent_distribution_cash_rent_1500_to_1999",
    "gross_rent_distribution_cash_rent_2000_plus",
    "gross_rent_distribution_cash_rent_2000_to_2499",
    "gross_rent_distribution_cash_rent_2500_to_2999",
    "gross_rent_distribution_cash_rent_3000_to_3499",
    "gross_rent_distribution_cash_rent_3500_plus",
    "gross_rent_distribution_no_cash_rent",
    "contract_rent_distribution_total",
    "contract_rent_distribution_with_cash_rent",
    "contract_rent_distribution_cash_rent_lt_100",
    "contract_rent_distribution_cash_rent_100_to_149",
    "contract_rent_distribution_cash_rent_150_to_199",
    "contract_rent_distribution_cash_rent_200_to_249",
    "contract_rent_distribution_cash_rent_250_to_299",
    "contract_rent_distribution_cash_rent_300_to_349",
    "contract_rent_distribution_cash_rent_350_to_399",
    "contract_rent_distribution_cash_rent_400_to_449",
    "contract_rent_distribution_cash_rent_450_to_499",
    "contract_rent_distribution_cash_rent_500_to_549",
    "contract_rent_distribution_cash_rent_550_to_599",
    "contract_rent_distribution_cash_rent_600_to_649",
    "contract_rent_distribution_cash_rent_650_to_699",
    "contract_rent_distribution_cash_rent_700_to_749",
    "contract_rent_distribution_cash_rent_750_to_799",
    "contract_rent_distribution_cash_rent_800_to_899",
    "contract_rent_distribution_cash_rent_900_to_999",
    "contract_rent_distribution_cash_rent_1000_to_1249",
    "contract_rent_distribution_cash_rent_1250_to_1499",
    "contract_rent_distribution_cash_rent_1500_to_1999",
    "contract_rent_distribution_cash_rent_2000_plus",
    "contract_rent_distribution_cash_rent_2000_to_2499",
    "contract_rent_distribution_cash_rent_2500_to_2999",
    "contract_rent_distribution_cash_rent_3000_to_3499",
    "contract_rent_distribution_cash_rent_3500_plus",
    "contract_rent_distribution_no_cash_rent",
    "gross_rent_pct_income_total",
    "gross_rent_pct_income_lt_10",
    "gross_rent_pct_income_10_to_14_9",
    "gross_rent_pct_income_15_to_19_9",
    "gross_rent_pct_income_20_to_24_9",
    "gross_rent_pct_income_25_to_29_9",
    "gross_rent_pct_income_30_to_34_9",
    "gross_rent_pct_income_35_to_39_9",
    "gross_rent_pct_income_40_to_49_9",
    "gross_rent_pct_income_50_plus",
    "gross_rent_pct_income_not_computed",
    "owner_costs_pct_income_total",
    "owner_costs_pct_income_with_mortgage_total",
    "owner_costs_pct_income_with_mortgage_lt_10",
    "owner_costs_pct_income_with_mortgage_10_to_14_9",
    "owner_costs_pct_income_with_mortgage_15_to_19_9",
    "owner_costs_pct_income_with_mortgage_20_to_24_9",
    "owner_costs_pct_income_with_mortgage_25_to_29_9",
    "owner_costs_pct_income_with_mortgage_30_to_34_9",
    "owner_costs_pct_income_with_mortgage_35_to_39_9",
    "owner_costs_pct_income_with_mortgage_40_to_49_9",
    "owner_costs_pct_income_with_mortgage_50_plus",
    "owner_costs_pct_income_with_mortgage_not_computed",
    "owner_costs_pct_income_without_mortgage_total",
    "owner_costs_pct_income_without_mortgage_lt_10",
    "owner_costs_pct_income_without_mortgage_10_to_14_9",
    "owner_costs_pct_income_without_mortgage_15_to_19_9",
    "owner_costs_pct_income_without_mortgage_20_to_24_9",
    "owner_costs_pct_income_without_mortgage_25_to_29_9",
    "owner_costs_pct_income_without_mortgage_30_to_34_9",
    "owner_costs_pct_income_without_mortgage_35_to_39_9",
    "owner_costs_pct_income_without_mortgage_40_to_49_9",
    "owner_costs_pct_income_without_mortgage_50_plus",
    "owner_costs_pct_income_without_mortgage_not_computed",
    "tenure_income_total",
    "tenure_income_owner_occupied_total",
    "tenure_income_owner_occupied_lt_5000",
    "tenure_income_owner_occupied_5000_to_9999",
    "tenure_income_owner_occupied_10000_to_14999",
    "tenure_income_owner_occupied_15000_to_19999",
    "tenure_income_owner_occupied_20000_to_24999",
    "tenure_income_owner_occupied_25000_to_34999",
    "tenure_income_owner_occupied_35000_to_49999",
    "tenure_income_owner_occupied_50000_to_74999",
    "tenure_income_owner_occupied_75000_to_99999",
    "tenure_income_owner_occupied_100000_to_149999",
    "tenure_income_owner_occupied_150000_plus",
    "tenure_income_renter_occupied_total",
    "tenure_income_renter_occupied_lt_5000",
    "tenure_income_renter_occupied_5000_to_9999",
    "tenure_income_renter_occupied_10000_to_14999",
    "tenure_income_renter_occupied_15000_to_19999",
    "tenure_income_renter_occupied_20000_to_24999",
    "tenure_income_renter_occupied_25000_to_34999",
    "tenure_income_renter_occupied_35000_to_49999",
    "tenure_income_renter_occupied_50000_to_74999",
    "tenure_income_renter_occupied_75000_to_99999",
    "tenure_income_renter_occupied_100000_to_149999",
    "tenure_income_renter_occupied_150000_plus",
    "owner_occupied_value_total",
    "owner_occupied_value_lt_10000",
    "owner_occupied_value_10000_to_14999",
    "owner_occupied_value_15000_to_19999",
    "owner_occupied_value_20000_to_24999",
    "owner_occupied_value_25000_to_29999",
    "owner_occupied_value_30000_to_34999",
    "owner_occupied_value_35000_to_39999",
    "owner_occupied_value_40000_to_49999",
    "owner_occupied_value_50000_to_59999",
    "owner_occupied_value_60000_to_69999",
    "owner_occupied_value_70000_to_79999",
    "owner_occupied_value_80000_to_89999",
    "owner_occupied_value_90000_to_99999",
    "owner_occupied_value_100000_to_124999",
    "owner_occupied_value_125000_to_149999",
    "owner_occupied_value_150000_to_174999",
    "owner_occupied_value_175000_to_199999",
    "owner_occupied_value_200000_to_249999",
    "owner_occupied_value_250000_to_299999",
    "owner_occupied_value_300000_to_399999",
    "owner_occupied_value_400000_to_499999",
    "owner_occupied_value_500000_to_749999",
    "owner_occupied_value_750000_to_999999",
    "owner_occupied_value_1000000_plus",
    "owner_occupied_value_1000000_to_1499999",
    "owner_occupied_value_1500000_to_1999999",
    "owner_occupied_value_2000000_plus",
    "educational_attainment_25plus_total",
    "educational_attainment_25plus_no_schooling_completed",
    "educational_attainment_25plus_nursery_school",
    "educational_attainment_25plus_kindergarten",
    "educational_attainment_25plus_1st_grade",
    "educational_attainment_25plus_2nd_grade",
    "educational_attainment_25plus_3rd_grade",
    "educational_attainment_25plus_4th_grade",
    "educational_attainment_25plus_5th_grade",
    "educational_attainment_25plus_6th_grade",
    "educational_attainment_25plus_7th_grade",
    "educational_attainment_25plus_8th_grade",
    "educational_attainment_25plus_9th_grade",
    "educational_attainment_25plus_10th_grade",
    "educational_attainment_25plus_11th_grade",
    "educational_attainment_25plus_12th_grade_no_diploma",
    "educational_attainment_25plus_high_school_diploma",
    "educational_attainment_25plus_ged_or_alternative_credential",
    "educational_attainment_25plus_some_college_lt_1_year",
    "educational_attainment_25plus_some_college_1plus_year_no_degree",
    "educational_attainment_25plus_associates_degree",
    "educational_attainment_25plus_bachelors_degree",
    "educational_attainment_25plus_masters_degree",
    "educational_attainment_25plus_professional_school_degree",
    "educational_attainment_25plus_doctorate_degree",
]

SAE_COMPONENT_COLUMNS: list[str] = [f"sae_{column}" for column in ACS5_SAE_COUNT_COLUMNS]

SAE_DERIVED_MEASURE_COLUMNS: list[str] = [
    "sae_household_income_quintile_cutoff_20",
    "sae_household_income_quintile_cutoff_40",
    "sae_household_income_median",
    "sae_household_income_quintile_cutoff_60",
    "sae_household_income_quintile_cutoff_80",
    "sae_gross_rent_median",
    "sae_contract_rent_median",
    "sae_rent_burden_30_plus",
    "sae_rent_burden_50_plus",
    "sae_owner_cost_burden_30_plus",
    "sae_owner_cost_burden_50_plus",
    "sae_civilian_labor_force",
    "sae_unemployed_count",
    "sae_unemployment_rate",
]

SAE_DIAGNOSTIC_COLUMNS: list[str] = [
    "sae_source_county_count",
    "sae_source_counties",
    "sae_crosswalk_tract_count",
    "sae_allocated_tract_count",
    "sae_missing_allocation_tract_count",
    "sae_crosswalk_coverage_ratio",
    "sae_crosswalk_share_sum",
    "sae_nan_share_tract_count",
    "sae_missing_support_count",
    "sae_zero_denominator_count",
    "sae_partial_coverage_count",
    "sae_direct_county_comparable",
    "sae_direct_county_comparability_reason",
    "sae_direct_county_absolute_difference",
    "sae_direct_county_relative_difference",
]

SAE_LINEAGE_COLUMNS: list[str] = [
    "acs1_vintage_used",
    "acs5_vintage_used",
    "tract_vintage_used",
    "sae_allocation_method",
    "sae_denominator_source",
    "sae_crosswalk_id",
]

SAE_MEASURE_COLUMNS: list[str] = [
    *SAE_DERIVED_MEASURE_COLUMNS,
]

SAE_OUTPUT_COLUMNS: list[str] = [
    "geo_type",
    "geo_id",
    "year",
    *SAE_LINEAGE_COLUMNS,
    *SAE_MEASURE_COLUMNS,
    *SAE_DIAGNOSTIC_COLUMNS,
]

ACS1_IMPUTATION_LINEAGE_COLUMNS: list[str] = [
    "acs1_vintage_used",
    "acs5_vintage_used",
    "tract_vintage_used",
    "acs1_imputation_method",
    "acs1_imputation_denominator_source",
    "acs1_imputation_crosswalk_id",
]

ACS1_IMPUTATION_FLAG_COLUMNS: list[str] = [
    "is_modeled",
    "is_synthetic",
]

ACS1_IMPUTATION_DIAGNOSTIC_COLUMNS: list[str] = [
    "acs1_imputation_source_county_count",
    "acs1_imputation_tract_count",
    "acs1_imputation_zero_denominator_count",
    "acs1_imputation_missing_support_count",
    "acs1_imputation_validation_abs_diff",
    "acs1_imputation_validation_rel_diff",
]

ACS1_IMPUTATION_BASE_OUTPUT_COLUMNS: list[str] = [
    "geo_type",
    "geo_id",
    "year",
    "target_geo_type",
    "target_geo_id",
    "county_fips",
    "tract_geoid",
    *ACS1_IMPUTATION_LINEAGE_COLUMNS,
    *ACS1_IMPUTATION_FLAG_COLUMNS,
]

ACS5_COUNT_COLUMNS: list[str] = [
    TOTAL_POPULATION,
    "adult_population",
    "total_housing_units",
    "occupied_housing_units",
    "vacant_housing_units",
    "total_households",
    "owner_households",
    "renter_households",
    "poverty_universe",
    "below_50pct_poverty",
    "50_to_99pct_poverty",
    "population_below_poverty",
    "civilian_labor_force",
    "unemployed_count",
    *ACS5_SAE_COUNT_COLUMNS,
]

ACS5_MEDIAN_COLUMNS: list[str] = [
    "median_household_income",
    "per_capita_income",
    "median_gross_rent",
    "median_contract_rent",
    "median_owner_occupied_home_value",
    "gini_index",
]

ACS5_MOE_COLUMNS: list[str] = [
    "moe_total_population",
]

ACS5_DERIVED_COLUMNS: list[str] = [
    "adult_population",
    "population_below_poverty",
    "poverty_rate",
    "unemployment_rate",
    "vacancy_rate",
    "rent_burden_30_plus",
]

ACS_TRACT_OUTPUT_COLUMNS: list[str] = [
    "tract_geoid",
    "acs_vintage",
    "tract_vintage",
    TOTAL_POPULATION,
    "moe_total_population",
    "adult_population",
    "total_housing_units",
    "occupied_housing_units",
    "vacant_housing_units",
    "total_households",
    "owner_households",
    "renter_households",
    "median_household_income",
    "per_capita_income",
    "median_gross_rent",
    "median_contract_rent",
    "median_owner_occupied_home_value",
    "gini_index",
    "poverty_universe",
    "below_50pct_poverty",
    "50_to_99pct_poverty",
    "population_below_poverty",
    "civilian_labor_force",
    "unemployed_count",
    *ACS5_SAE_COUNT_COLUMNS,
    "data_source",
    "source_ref",
    "ingested_at",
]

PEP_COUNTY_OUTPUT_COLUMNS: list[str] = [
    "county_fips",
    "state_fips",
    "county_name",
    "state_name",
    "year",
    "reference_date",
    "population",
    "estimate_type",
    "vintage",
    "data_source",
    "source_url",
    "raw_sha256",
    "ingested_at",
]

MEDSL_COUNTY_PRESIDENTIAL_OUTPUT_COLUMNS: list[str] = [
    "geo_type",
    "geo_id",
    "county_fips",
    "state",
    "state_po",
    "county_name",
    "year",
    "office",
    "candidate",
    "party",
    "party_simplified",
    "candidatevotes",
    "totalvotes",
    "source_version",
    "data_source",
    "source_url",
    "source_doi",
    "raw_sha256",
    "ingested_at",
]

MEDSL_PRESIDENT_COUNTY_MEASURE_COLUMNS: list[str] = [
    "geo_type",
    "geo_id",
    "county_fips",
    "county_vintage",
    "year",
    "democratic_votes",
    "republican_votes",
    "two_party_votes",
    "totalvotes",
    "democratic_vote_share",
    "republican_vote_share",
    "democratic_republican_vote_ratio",
    "republican_democratic_vote_ratio",
    "democratic_margin",
    "major_party_vote_share",
    "data_source",
    "source_url",
    "source_version",
    "raw_sha256",
]

VERA_INCARCERATION_COUNTY_MEASURE_COLUMNS: list[str] = [
    "geo_type",
    "geo_id",
    "county_fips",
    "county_vintage",
    "year",
    "county_name",
    "state_abbr",
    "state_fips",
    "urbanicity",
    "region",
    "division",
    "metro_area",
    "commuting_zone",
    "land_area",
    "is_regional_jail",
    "is_unified_state",
    "total_jail_pop",
    "male_jail_pop",
    "female_jail_pop",
    "black_jail_pop",
    "latinx_jail_pop",
    "white_jail_pop",
    "native_jail_pop",
    "aapi_jail_pop",
    "other_race_jail_pop",
    "total_pretrial_custody",
    "total_sentenced_custody",
    "total_jail_admits",
    "male_jail_admits",
    "female_jail_admits",
    "total_jail_discharges",
    "male_jail_discharges",
    "female_jail_discharges",
    "jail_rated_capacity",
    "total_prison_pop",
    "male_prison_pop",
    "female_prison_pop",
    "black_prison_pop",
    "latinx_prison_pop",
    "white_prison_pop",
    "native_prison_pop",
    "aapi_prison_pop",
    "other_race_prison_pop",
    "total_prison_admits",
    "male_prison_admits",
    "female_prison_admits",
    "total_pop_15to64",
    "male_pop_15to64",
    "female_pop_15to64",
    "black_pop_15to64",
    "latinx_pop_15to64",
    "white_pop_15to64",
    "native_pop_15to64",
    "aapi_pop_15to64",
    "total_incarceration",
    "data_source",
    "source_url",
    "source_version",
    "raw_sha256",
    "ingested_at",
]

URBAN_AREA_GEOMETRY_COLUMNS: tuple[str, ...] = (
    "urban_area_geoid",
    "urban_area_name",
    "urban_area_type",
    "urban_area_vintage",
    "data_source",
    "source_ref",
    "ingested_at",
    "geometry",
)

BLOCK_GEOMETRY_COLUMNS: tuple[str, ...] = (
    "block_geoid",
    "state_fips",
    "county_fips",
    "tract_geoid",
    "block_vintage",
    "data_source",
    "source_ref",
    "ingested_at",
    "geometry",
)

PL_BLOCK_POPULATION_COLUMNS: tuple[str, ...] = (
    "block_geoid",
    "state_fips",
    "county_fips",
    "tract_geoid",
    "block_vintage",
    "decennial_vintage",
    TOTAL_POPULATION,
    "data_source",
    "source_ref",
    "ingested_at",
)

COC_URBAN_FRACTION_COLUMNS: tuple[str, ...] = (
    "coc_id",
    "boundary_vintage",
    "urban_area_vintage",
    "block_vintage",
    "decennial_vintage",
    "denominator_source",
    "allocation_method",
    "classification_method",
    "coc_total_population",
    "coc_urban_population",
    "coc_rural_population",
    "urban_population_fraction",
    "block_count",
    "urban_block_count",
    "rural_block_count",
    "missing_denominator_block_count",
    "population_coverage_ratio",
    "source",
)

COC_URBAN_AREA_DETAIL_COLUMNS: tuple[str, ...] = (
    "coc_id",
    "urban_area_geoid",
    "urban_area_name",
    "boundary_vintage",
    "urban_area_vintage",
    "block_vintage",
    "decennial_vintage",
    "denominator_source",
    "allocation_method",
    "classification_method",
    TOTAL_POPULATION,
    "urban_population",
    "urban_population_fraction",
    "block_count",
    "source",
)

PIT_CANONICAL_COLUMNS: list[str] = [
    "pit_year",
    "coc_id",
    "pit_total",
    "pit_sheltered",
    "pit_unsheltered",
    "data_source",
    "source_ref",
    "ingested_at",
    "notes",
]

HIC_PROJECT_TYPES: tuple[str, ...] = ("es", "th", "sh", "rrh", "psh", "oph")

HIC_EXPANDED_BED_MEASURE_COLUMNS: tuple[str, ...] = tuple(
    f"hic_{project_type}_year_round_beds" for project_type in HIC_PROJECT_TYPES
)

HIC_EXPANDED_UNIT_MEASURE_COLUMNS: tuple[str, ...] = tuple(
    f"hic_{project_type}_family_units" for project_type in HIC_PROJECT_TYPES
)

HIC_DERIVED_MEASURE_COLUMNS: tuple[str, ...] = (
    "hic_shelter_year_round_beds",
    "hic_shelter_family_units",
    "hic_total_beds",
    "hic_total_units",
)

HIC_EXPANDED_MEASURE_COLUMNS: tuple[str, ...] = (
    *HIC_EXPANDED_BED_MEASURE_COLUMNS,
    *HIC_EXPANDED_UNIT_MEASURE_COLUMNS,
    *HIC_DERIVED_MEASURE_COLUMNS,
)

HIC_CANONICAL_COLUMNS: list[str] = [
    "hic_year",
    "coc_id",
    "coc_name",
    "state",
    "total_beds",
    "total_units",
    *HIC_EXPANDED_MEASURE_COLUMNS,
    "data_source",
    "source_ref",
    "ingested_at",
    "notes",
]

HIC_EXPANDED_MEASURE_SCHEMA: tuple[dict[str, object], ...] = (
    *(
        {
            "column": column,
            "measure": "year_round_beds",
            "project_type": project_type,
            "unit": "beds",
            "aggregation": "sum",
            "semantics": f"HUD year-round beds for {project_type.upper()} projects.",
            "historical_missing": (
                "Filled as 0 when the project type predates a distinct HUD HIC column; "
                "null only when the source column exists but the value is blank or "
                "non-numeric."
            ),
            "first_distinct_hud_year": {
                "es": 2014,
                "th": 2014,
                "sh": 2014,
                "rrh": 2013,
                "psh": 2010,
                "oph": 2014,
            }[project_type],
        }
        for project_type, column in zip(
            HIC_PROJECT_TYPES,
            HIC_EXPANDED_BED_MEASURE_COLUMNS,
            strict=True,
        )
    ),
    *(
        {
            "column": column,
            "measure": "family_units",
            "project_type": project_type,
            "unit": "units",
            "aggregation": "sum",
            "semantics": (
                f"HUD units for households with children for {project_type.upper()} projects."
            ),
            "historical_missing": (
                "Filled as 0 when the project type predates a distinct HUD HIC column; "
                "null only when the source column exists but the value is blank or "
                "non-numeric."
            ),
            "first_distinct_hud_year": {
                "es": 2014,
                "th": 2014,
                "sh": 2014,
                "rrh": 2013,
                "psh": 2010,
                "oph": 2014,
            }[project_type],
        }
        for project_type, column in zip(
            HIC_PROJECT_TYPES,
            HIC_EXPANDED_UNIT_MEASURE_COLUMNS,
            strict=True,
        )
    ),
    {
        "column": "hic_shelter_year_round_beds",
        "measure": "year_round_beds",
        "project_type": "es_th_sh",
        "unit": "beds",
        "aggregation": "sum",
        "semantics": "Shelter-only HUD total: ES + TH + SH year-round beds.",
        "historical_missing": (
            "Taken from HUD aggregate ES/TH/SH columns where available; otherwise "
            "derived from distinct ES, TH, and SH columns."
        ),
        "first_distinct_hud_year": 2010,
    },
    {
        "column": "hic_shelter_family_units",
        "measure": "family_units",
        "project_type": "es_th_sh",
        "unit": "units",
        "aggregation": "sum",
        "semantics": "Shelter-only HUD total: ES + TH + SH family units.",
        "historical_missing": (
            "Taken from HUD aggregate ES/TH/SH columns where available; otherwise "
            "derived from distinct ES, TH, and SH columns."
        ),
        "first_distinct_hud_year": 2010,
    },
    {
        "column": "hic_total_beds",
        "measure": "year_round_beds",
        "project_type": "all_programs",
        "unit": "beds",
        "aggregation": "sum",
        "semantics": "All-program total: ES + TH + SH + RRH + PSH + OPH year-round beds.",
        "historical_missing": (
            "Derived from project-type components, with historically absent project "
            "types filled as 0."
        ),
        "first_distinct_hud_year": 2010,
    },
    {
        "column": "hic_total_units",
        "measure": "family_units",
        "project_type": "all_programs",
        "unit": "units",
        "aggregation": "sum",
        "semantics": "All-program total: ES + TH + SH + RRH + PSH + OPH family units.",
        "historical_missing": (
            "Derived from project-type components, with historically absent project "
            "types filled as 0."
        ),
        "first_distinct_hud_year": 2010,
    },
)

HIC_PANEL_MEASURE_COLUMNS: list[str] = list(HIC_EXPANDED_MEASURE_COLUMNS)

ZORI_INGEST_OUTPUT_COLUMNS: list[str] = [
    "geo_type",
    "geo_id",
    "date",
    "year",
    "month",
    "zori",
    "region_name",
    "state",
    "data_source",
    "metric",
    "ingested_at",
    "source_ref",
    "raw_sha256",
]

LAUS_METRO_OUTPUT_COLUMNS: list[str] = [
    "metro_id",
    "metro_name",
    "definition_version",
    "year",
    "cbsa_code",
    "labor_force",
    "employed",
    "unemployed",
    "unemployment_rate",
    "data_source",
    "series_ids",
    "source_ref",
    "ingested_at",
]

TRACT_MEDIATED_DENOMINATOR_COLUMNS: dict[str, str] = {
    "area": "tract_area",
    "population": TOTAL_POPULATION,
    "household": "total_households",
    "renter_household": "renter_households",
}

TRACT_MEDIATED_WEIGHT_COLUMNS: tuple[str, ...] = (
    "area_weight",
    "population_weight",
    "household_weight",
    "renter_household_weight",
)

TRACT_MEDIATED_COUNTY_XWALK_COLUMNS: tuple[str, ...] = (
    "geo_id",
    "boundary_vintage",
    "county_fips",
    "county_vintage",
    "tract_vintage",
    "acs_vintage",
    "denominator_source",
    "denominator_vintage",
    "county_vintage_semantics",
    "weighting_method",
    "area_weight",
    "population_weight",
    "household_weight",
    "renter_household_weight",
    "area_denominator",
    "population_denominator",
    "household_denominator",
    "renter_household_denominator",
    "county_area_total",
    "county_population_total",
    "county_household_total",
    "county_renter_household_total",
    "geo_area_total",
    "geo_population_total",
    "geo_household_total",
    "geo_renter_household_total",
    "county_area_coverage_ratio",
    "county_population_coverage_ratio",
    "county_household_coverage_ratio",
    "county_renter_household_coverage_ratio",
    "tract_count",
    "denominator_tract_count",
    "missing_denominator_tract_count",
    "denominator_tract_coverage_ratio",
    "county_tract_count",
    "county_denominator_tract_count",
    "county_missing_denominator_tract_count",
    "county_denominator_tract_coverage_ratio",
    "missing_population_tract_count",
    "missing_household_tract_count",
    "missing_renter_household_tract_count",
)

COC_PANEL_COLUMNS: list[str] = [
    "coc_id",
    "year",
    "pit_total",
    "pit_sheltered",
    "pit_unsheltered",
    "boundary_vintage_used",
    "acs5_vintage_used",
    "tract_vintage_used",
    "alignment_type",
    "weighting_method",
    TOTAL_POPULATION,
    POPULATION_DENSITY_COLUMN,
    "adult_population",
    "population_below_poverty",
    "median_household_income",
    "median_gross_rent",
    "unemployment_rate",
    "coverage_ratio",
    "boundary_changed",
    "source",
]

METRO_PANEL_COLUMNS: list[str] = [
    "metro_id",
    "metro_name",
    "geo_type",
    "geo_id",
    "year",
    "pit_total",
    "pit_sheltered",
    "pit_unsheltered",
    "definition_version_used",
    "acs5_vintage_used",
    "tract_vintage_used",
    "alignment_type",
    "weighting_method",
    TOTAL_POPULATION,
    "adult_population",
    "population_below_poverty",
    "median_household_income",
    "median_gross_rent",
    "unemployment_rate_acs1",
    "labor_force",
    "employed",
    "unemployed",
    "unemployment_rate",
    "coverage_ratio",
    "boundary_changed",
    "acs1_vintage_used",
    "laus_vintage_used",
    "source",
]

MSA_PANEL_COLUMNS: list[str] = [
    "msa_id",
    "msa_name",
    "cbsa_code",
    "geo_type",
    "geo_id",
    "year",
    "pit_total",
    "pit_sheltered",
    "pit_unsheltered",
    "definition_version_used",
    "acs5_vintage_used",
    "tract_vintage_used",
    "alignment_type",
    "weighting_method",
    TOTAL_POPULATION,
    "adult_population",
    "population_below_poverty",
    "median_household_income",
    "median_gross_rent",
    "population",
    "coverage_ratio",
    "boundary_changed",
    "source",
]

MSA_COC_PANEL_COLUMNS: list[str] = [
    "msa_id",
    "coc_id",
    "year",
    "msa_population",
    "msa_median_rent",
    "msa_vacancy_rate",
    "msa_poverty_rate",
    "msa_unemployment",
    "msa_income",
    "msa_rent_burden",
    "pit_total",
    "pit_sheltered",
    "pit_unsheltered",
    "coc_population",
    "ranking_population_source",
    "ranking_reference_year",
    "containment_min_share",
    "containment_denominator",
    "coc_boundary_vintage_used",
    "msa_definition_version_used",
    "msa_population_source",
    "unemployment_source",
    "source",
]

MSA_COC_COVERAGE_COLUMNS: tuple[str, ...] = (
    "msa_id",
    "msa_name",
    "year",
    "coc_id",
    "coc_name",
    "overlap_basis",
    "denominator_source",
    "denominator_vintage",
    "denominator_column",
    "msa_covered_by_coc_percent",
    "coc_contained_in_msa_percent",
    "intersection_value",
    "msa_denominator",
    "coc_denominator",
    "boundary_vintage",
    "county_vintage",
    "definition_version",
    "top_n",
    "ranking_population_source",
    "ranking_reference_year",
)

MSA_FRACTIONAL_ROLLUP_COLUMNS: tuple[str, ...] = (
    "msa_id",
    "year",
    "source_dataset_id",
    "source_geo_type",
    "source_additive_measure_columns",
    "native_msa_covariate_columns",
    "allocation_basis",
    "denominator_source",
    "boundary_vintage",
    "county_vintage",
    "block_vintage",
    "decennial_vintage",
    "msa_definition_version",
    "coc_count",
    "covered_coc_count",
    "missing_coc_count",
    "missing_cocs",
    "unmapped_source_coc_count",
    "unmapped_source_cocs",
    "unmapped_source_additive_measure_totals",
    "zero_population_coc_count",
    "missing_population_block_count",
    "min_coc_population_containment_share",
    "min_msa_population_coverage_share",
    "min_allocation_share",
    "coc_population_coverage_ratio",
    "msa_population_coverage_ratio",
    "allocation_share_sum",
    "expected_allocation_share_sum",
    "source",
)

PRIMARY_MSA_ANNOTATION_COLUMNS: tuple[str, ...] = (
    "coc_id",
    "primary_msa_id",
    "primary_msa_name",
    "primary_msa_population",
    "primary_msa_overlap_basis",
    "primary_msa_coc_contained_percent",
    "primary_msa_covered_by_coc_percent",
)

ZORI_COLUMNS: list[str] = [
    "zori_coc",
    "zori_coverage_ratio",
    "zori_is_eligible",
    "zori_excluded_reason",
    "rent_to_income",
]

ZORI_PROVENANCE_COLUMNS: list[str] = [
    "rent_metric",
    "rent_alignment",
    "zori_min_coverage",
]

DRIFT_PRONE_SOURCE_COLUMNS: tuple[str, ...] = (
    "population",
    "coverage_ratio",
    "source_year",
)
