"""README generation utilities for export bundles.

This module provides functions to generate and write README.md files
for CoC Lab export bundles, including usage instructions and attribution.
"""

from pathlib import Path


def generate_readme(manifest: dict, bundle_name: str) -> str:
    """Generate README.md content for an export bundle.

    Args:
        manifest: The MANIFEST.json dict containing bundle metadata
        bundle_name: Name of the bundle

    Returns:
        Markdown content for README.md
    """
    lines: list[str] = []

    # Header with bundle name
    lines.append(f"# {bundle_name}")
    lines.append("")

    # Creation date and version info
    created_at = manifest.get("created_at_utc", "Unknown")
    lines.append(f"**Created:** {created_at}")
    lines.append("")

    # CoC Lab version
    coclab_info = manifest.get("coclab", {})
    if coclab_info:
        version = coclab_info.get("version", "Unknown")
        lines.append(f"**Generated by:** CoC Lab v{version}")
        git_commit = coclab_info.get("git_commit")
        if git_commit:
            lines.append(f"**Git commit:** {git_commit}")
        lines.append("")

    # Parameters section
    params = manifest.get("parameters", {})
    if params:
        lines.append("## Parameters")
        lines.append("")
        if params.get("boundary_vintage"):
            lines.append(f"- **Boundary vintage:** {params['boundary_vintage']}")
        if params.get("tract_vintage"):
            lines.append(f"- **Tract vintage:** {params['tract_vintage']}")
        if params.get("county_vintage"):
            lines.append(f"- **County vintage:** {params['county_vintage']}")
        if params.get("acs_vintage"):
            lines.append(f"- **ACS vintage:** {params['acs_vintage']}")
        if params.get("years"):
            lines.append(f"- **Years:** {params['years']}")
        lines.append("")

    # What's included section
    artifacts = manifest.get("artifacts", [])
    if artifacts:
        lines.append("## Contents")
        lines.append("")

        # Group artifacts by role
        by_role: dict[str, list[dict]] = {}
        for artifact in artifacts:
            role = artifact.get("role", "other")
            if role not in by_role:
                by_role[role] = []
            by_role[role].append(artifact)

        # Display in a logical order
        role_order = ["panel", "input", "derived", "diagnostic", "codebook", "other"]
        role_labels = {
            "panel": "Panel Data",
            "input": "Input Data",
            "derived": "Derived Artifacts",
            "diagnostic": "Diagnostics",
            "codebook": "Codebook",
            "other": "Other Files",
        }

        for role in role_order:
            if role in by_role:
                lines.append(f"### {role_labels.get(role, role.title())}")
                lines.append("")
                for artifact in by_role[role]:
                    path = artifact.get("path", "Unknown")
                    rows = artifact.get("rows")
                    columns = artifact.get("columns")
                    size_bytes = artifact.get("bytes")

                    # Format size nicely
                    size_str = ""
                    if size_bytes is not None:
                        if size_bytes >= 1_000_000:
                            size_str = f" ({size_bytes / 1_000_000:.1f} MB)"
                        elif size_bytes >= 1_000:
                            size_str = f" ({size_bytes / 1_000:.1f} KB)"
                        else:
                            size_str = f" ({size_bytes} bytes)"

                    # Build description
                    desc_parts = []
                    if rows is not None:
                        desc_parts.append(f"{rows:,} rows")
                    if columns is not None:
                        desc_parts.append(f"{columns} columns")

                    desc = ""
                    if desc_parts:
                        desc = f" - {', '.join(desc_parts)}"

                    lines.append(f"- `{path}`{size_str}{desc}")
                lines.append("")

    # DVC usage section
    lines.append("## Using this bundle in an analysis repository")
    lines.append("")
    lines.append("Recommended: track this folder with DVC.")
    lines.append("")
    lines.append("```bash")
    lines.append("dvc init")
    lines.append("dvc add path/to/this/bundle")
    lines.append("git add path/to/bundle.dvc .gitignore")
    lines.append('git commit -m "Pin CoC Lab export bundle"')
    lines.append("```")
    lines.append("")
    lines.append("All analysis code should refer only to paths inside this bundle.")
    lines.append("The `MANIFEST.json` file pins exact file hashes for provenance.")
    lines.append("")

    # Attribution section for external sources
    sources = manifest.get("sources", [])
    if sources:
        lines.append("## Data Sources and Attribution")
        lines.append("")
        for source in sources:
            name = source.get("name", "Unknown Source")
            lines.append(f"### {name}")
            lines.append("")
            metric = source.get("metric")
            if metric:
                lines.append(f"**Metric:** {metric}")
                lines.append("")
            attribution = source.get("attribution")
            if attribution:
                lines.append(f"> {attribution}")
                lines.append("")
            license_notes = source.get("license_notes")
            if license_notes:
                lines.append(f"**License:** {license_notes}")
                lines.append("")

    # Notes section if present
    notes = manifest.get("notes")
    if notes:
        lines.append("## Notes")
        lines.append("")
        lines.append(notes)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(
        "*This README was auto-generated by CoC Lab. "
        "See MANIFEST.json for complete provenance metadata.*"
    )
    lines.append("")

    return "\n".join(lines)


def write_readme(bundle_root: Path, content: str) -> Path:
    """Write README.md to bundle root.

    Args:
        bundle_root: Root directory of export bundle
        content: README markdown content

    Returns:
        Path to written README.md
    """
    readme_path = bundle_root / "README.md"
    readme_path.write_text(content, encoding="utf-8")
    return readme_path
